# Generated by Django 6.0.3 on 2026-04-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enroll', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
